In [ ]:
import numpy as np

In [ ]:
x=float(input('Ingrese las coordenadas x='))
y=float(input('Ingrese las coordenadas y='))
z=float(input('Ingrese las coordenadas z='))

#Coordenadas cilíndricas

r=np.sqrt((x**2)+(y**2))
theta=np.arctan(y/x)
thetadeg=np.rad2deg(theta)

print('Las coordenadas cilíndricas son [r,thetadeg,z]')
print([r,thetadeg,z])



#Coordenadas esféricas
r1=np.sqrt((x**2)+(y**2)+(z**2))
phi=np.arccos(z/r1)
phideg=np.rad2deg(phi)

print('Las coordenadas esféricas son [r1,thetadeg,phideg]')
print([r1,thetadeg,phideg])




Ingrese las coordenadas x=2
Ingrese las coordenadas y=3
Ingrese las coordenadas z=5
Las coordenadas cilíndricas son [r,thetadeg,z]
[3.605551275463989, 56.309932474020215, 5.0]
Las coordenadas esféricas son [r1,thetadeg,phideg]
[6.164414002968976, 56.309932474020215, 35.795759914707084]


In [ ]:
Puv=[[1],[2]];
theta=np.pi/2;
R=[[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]];
pxy=np.dot(R,Puv);
print('pxy=');
print(pxy)



theta2=np.pi/4;
R2=[[np.cos(theta2), -np.sin(theta2)], [np.sin(theta2), np.cos(theta2)]];
pxy2=np.dot(R2,Puv);
print('pxy2=');
print(pxy2);

pxy=
[[-2.]
 [ 1.]]
pxy2=
[[-0.70710678]
 [ 2.12132034]]


In [ ]:
Puv=[[1],[1],[2]];
theta=np.pi/2;
R=[[np.cos(theta), 0, np.sin(theta)], [0, 1, 0], [-np.sin(theta), 0,np.cos(theta)]]
pxy=np.dot(R,Puv);
print('pxy=');
print(pxy)



theta2=np.pi/4;
R2=[[np.cos(theta2), 0, np.sin(theta2)], [0, 1, 0], [-np.sin(theta2), 0,np.cos(theta2)]];
pxy2=np.dot(R2,Puv);
print('pxy2=');
print(pxy2);

pxy=
[[ 2.]
 [ 1.]
 [-1.]]
pxy2=
[[2.12132034]
 [1.        ]
 [0.70710678]]
